### PR TITLE
Fix macOS build, resolve clippy warnings, add Windows ARM64

### LINKED ISSUE #19: Pages out of order in final PDF
Just installed and tried it on a book twice and the pages are consistently out of order. FWIW, I am on macOS. Turning on the save-image option is a work-around for now because it lets me make my own PDF with the pages in the right order, but I thought you should know. Here's the book, if it matters. 

https://www.google.com/books/edition/The_Rudiments_of_Grammar_for_the_English/FodFAAAAcAAJ

Here's the last command and the verbose log, though it doesn't help any as there are no errors.

 gbscraper -k -v https://www.google.com/books/edition/The_Rudiments_of_Grammar_for_the_English/FodFAAAAcAAJ 
Identifying book: FodFAAAAcAAJ...
Attemping download of issue page with url: https://books.google.us/books?id=FodFAAAAcAAJ&hl=en
Found: The Rudiments of Grammar for the English-Saxon Tongue, First Given in English: With an Apology for the Study of Northern Antiquities
Parsing table of contents...
Downloading images...
Generating PDF...

### PR DESCRIPTION
**Pull request by Sekkyo**
This pull request introduces several improvements and fixes across the codebase, focusing on enhanced platform support, dependency updates, code simplification, bug fixes, and robustness improvements identified during code review. The most significant changes include fixing macOS builds by updating the `zip` crate configuration, adding Windows ARM64 build support, improving error handling and code clarity, fixing minor logic issues in the scraper and utility modules, and hardening the CBZ and PDF writers against silent failures and non-deterministic page ordering (Resolves #19).

**Platform and Dependency Updates:**

* Updated the `zip` crate to version 2.2.0, disabled default features, and enabled the `deflate-miniz` feature for more efficient and compatible CBZ/ZIP file creation. This is required for macOS compatibility (`Cargo.toml`).
* Added Windows ARM64 (`aarch64-pc-windows-msvc`) as a build target in the GitHub Actions release workflow, enabling distribution for more Windows devices (`.github/workflows/release.yml`).

**Code Quality and Error Handling Improvements:**

* Replaced deprecated or verbose error creation with the simpler `io::Error::other` and removed redundant doc comments, improving error handling throughout `src/lib/scraper/helpers.rs`. [[1]](src/lib/scraper/helpers.rs) [[2]](src/lib/scraper/helpers.rs)
* Simplified logic for extracting path segments using `.next_back()` instead of `.last()`, simplified `generate_image_filename` to a single `format!` call, and removed a redundant `.to_string()` call on a `Cow<str>`. [[1]](src/lib/scraper/helpers.rs) [[2]](src/lib/scraper/helpers.rs)

**Scraper Logic and Bug Fixes:**

* Removed unnecessary references and clones in function calls and variable assignments, reducing allocations and clarifying intent in `src/lib/scraper/batching.rs` and `src/lib/scraper/scraper.rs`. [[1]](src/lib/scraper/batching.rs) [[2]](src/lib/scraper/batching.rs) [[3]](src/lib/scraper/scraper.rs)
* Fixed logic for skipping pages without download links — the previous code had inverted `None`/`Some` checks that caused pages to be skipped incorrectly. Improved iteration over page children in metadata parsing by replacing a manual counter with `e.text().enumerate()`. [[1]](src/lib/scraper/scraper.rs) [[2]](src/lib/scraper/scraper.rs) [[3]](src/lib/scraper/types.rs)

**Writer Robustness (from code review):**

* Both `create_cbz` (`src/lib/writer/cbz.rs`) and `create_pdf_internal` (`src/lib/writer/pdf.rs`) now collect all `read_dir` entries eagerly via `collect::<io::Result<_>>()?`, propagating any entry-level I/O errors instead of silently dropping them with `.flatten()`.
* Entries are sorted by filename before processing, ensuring stable and deterministic page ordering across all platforms (the zero-padded filename prefix `00001-`, `00002-`, etc. now reliably determines page sequence). [[1]](src/lib/writer/cbz.rs) [[2]](src/lib/writer/pdf.rs)
* `File::open` failures in `create_cbz` now propagate as `io::Error` instead of silently skipping pages, preventing the creation of incomplete archives without any indication of failure. [[1]](src/lib/writer/cbz.rs)
* `lopdf::xobject::image()` failures in `create_pdf_internal` now propagate via `map_err(...)?` instead of being silently skipped via `if let Ok(stream) = ...`, preventing the creation of PDFs with missing pages. [[1]](src/lib/writer/pdf.rs)
* `doc.insert_image()` errors now propagate with a descriptive message via `io::Error::other(...)` instead of printing `"error!: {name}"` and continuing. [[1]](src/lib/writer/pdf.rs)
* `content.encode()`, filename `into_string()`, and path `.to_str()` conversions now return structured `io::Error` instead of panicking via `.unwrap()`. [[1]](src/lib/writer/pdf.rs)

**Utility and Miscellaneous:**

* `args.to_options().unwrap()` in `src/util/main.rs` now matches on the result, printing to stderr and calling `process::exit(1)` on error. `fs::read_to_string(file).unwrap()` is replaced with `?` propagation. [[1]](src/util/main.rs) [[2]](src/util/main.rs)
* Implemented the `Default` trait for `TableOfContents` in `src/lib/writer/pdf.rs` to satisfy Clippy's `new_without_default` lint. [[1]](src/lib/writer/pdf.rs)
* Added `#[allow(clippy::large_enum_variant)]` to `DownloadStatus` and `#[allow(clippy::module_inception)]` to `src/lib/scraper/mod.rs` to suppress relevant Clippy warnings. [[1]](src/lib/scraper/types.rs) [[2]](src/lib/scraper/mod.rs)
* Fixed typos in log messages ("Attemping" → "Attempting") and a comment ("propogation" → "propagation"). [[1]](src/lib/scraper/batching.rs) [[2]](src/lib/scraper/helpers.rs)

### CODE REVIEW

**Comment by shloop** [comment]
Much appreciated! This was my first project in Rust and I have not used Rust much or done much of any software development outside of work since starting my current job, so it will probably take me a while to refresh my memory and properly review this. At a glance everything looks fine though, and if there are no issues I will merge once I get a chance to review.

**Comment by Sekkyo** [comment]
@shloop No worries, and Rust is such an excellent language to work with for a command line utility like this. I'm learning it through a lot of Agentic GitOps, but applying three decades of experience working in software development and enterprise architecture across private organizations and public sector. The Rust linter `clippy` and formatter `rustfmt` are your best friends. Run them before every commit and they will catch so many issues in a super opinionated language like Rust.

I'm working on these Copilot findings for you now and applying them to this pull request.

**Comment by Sekkyo** [comment]
@shloop Apologies for the long PR and many commits. I had to fix more things the longer Copilot kept giving me feedback. My first commit -- or maybe this repo always had -- a page sort order issue I reproduced last night and have now fixed. There's more files and lines of code to look at now, but I'm a lot happier with this result.

File: src/lib/scraper/scraper.rs [hunk 1]
```diff
@@ -73,7 +73,7 @@ pub fn download_issue(
 
     // Check if image directory and any needed formats already exist on disk.
 
-    let mut formats = options.formats.clone();
+    let mut formats = options.formats;
```
Comment (shloop) [inline src/lib/scraper/scraper.rs]: This clone was intentional. Formats are removed in the clone if they already exist on disk, but this may be done in a batch operation where multiple issues of a magazine are downloaded so the formats need to remain intact in case a particular format was not already generated for a different issue.

I think the only reason I made the options mutable was so that the set of already downloaded issues could be updated, but that should probably be passed in as a separate argument now that I think about it. The rest of the data in the options comes directly from the command line args and should not be modified.

Comment (shloop) [inline src/lib/scraper/scraper.rs]:
```suggestion
    let mut formats = options.formats.clone();
```

**Review by shloop — CHANGES_REQUESTED** [review]
All looks good except for the part I commented on.

**Review by shloop — APPROVED** [review]
